@MulliganDeck.Api_HostAddress = http://localhost:5294

### Listar todas
GET http://localhost:5294/api/cartas

### Una que existe → 200
GET http://localhost:5294/api/cartas/2

### Una que no existe → 404
GET http://localhost:5294/api/cartas/999

### Crear (debería ignorar el id 99)
POST http://localhost:5294/api/cartas
Content-Type: application/json

{
  "id": 99,
  "nombre": "Rayo",
  "costeMana": 1,
  "color": "Rojo",
  "ataque": 0,
  "vida": 0
}

### Crear (Carta con coste negativo)
POST http://localhost:5294/api/cartas
Content-Type: application/json

{
  "id": 4,
  "nombre": "Rayo",
  "costeMana": -1,
  "color": "Rojo",
  "ataque": 0,
  "vida": 0
}

### Crear (Carta con varios errores)
POST http://localhost:5294/api/cartas
Content-Type: application/json

{
  "id": 4,
  "nombre": "",
  "costeMana": -1,
  "color": "Rojo",
  "ataque": 40,
  "vida": -10
}

### Actualizar (deberia ignorar id 99 y actualizar la carta con id 2)
PUT http://localhost:5294/api/cartas/2
Content-Type: application/json

{
  "id": 99,
  "nombre": "Engendro modificado",
  "costeMana": 3,
  "color": "Azul",
  "ataque": 2,
  "vida": 2
}

### Actualizar algo que no existe → 404
PUT http://localhost:5294/api/cartas/999
Content-Type: application/json

{ "id": 999, "nombre": "Fantasma", "costeMana": 1, "color": "Negro", "ataque": 1, "vida": 1 }

### Borrar → 204
DELETE http://localhost:5294/api/cartas/1

### Borrar lo ya borrado → 404
DELETE http://localhost:5294/api/cartas/1