// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MulliganDeck.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MulliganDeck.Infrastructure.Migrations
{
    [DbContext(typeof(MulliganDeckContext))]
    [Migration("20260814144903_AddUser")]
    partial class AddUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CardKeyword", b =>
                {
                    b.Property<Guid>("CardsOracleId")
                        .HasColumnType("uuid");

                    b.Property<int>("KeywordsId")
                        .HasColumnType("integer");

                    b.HasKey("CardsOracleId", "KeywordsId");

                    b.HasIndex("KeywordsId");

                    b.ToTable("CardKeyword");
                });

            modelBuilder.Entity("MulliganDeck.Domain.Card", b =>
                {
                    b.Property<Guid>("OracleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cmc")
                        .HasColumnType("numeric");

                    b.Property<string>("ColorIdentity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Colors")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("DefaultPrintingId")
                        .HasColumnType("uuid");

                    b.Property<string>("ManaCost")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OracleText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Power")
                        .HasColumnType("text");

                    b.Property<string>("Toughness")
                        .HasColumnType("text");

                    b.Property<string>("TypeLine")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("OracleId");

                    b.HasIndex("DefaultPrintingId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("MulliganDeck.Domain.CollectionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Foil")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PrintingId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PrintingId");

                    b.ToTable("CollectionItems");
                });

            modelBuilder.Entity("MulliganDeck.Domain.Deck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CommanderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CommanderId");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("MulliganDeck.Domain.DeckCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid");

                    b.Property<int>("DeckId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PrintingId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("DeckId");

                    b.HasIndex("PrintingId");

                    b.ToTable("DeckCard");
                });

            modelBuilder.Entity("MulliganDeck.Domain.Keyword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Keywords");
                });

            modelBuilder.Entity("MulliganDeck.Domain.Legality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("Legalities", (string)null);
                });

            modelBuilder.Entity("MulliganDeck.Domain.Printing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Artist")
                        .HasColumnType("text");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid");

                    b.Property<int?>("CardmarketId")
                        .HasColumnType("integer");

                    b.Property<string>("CollectorNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FlavorText")
                        .HasColumnType("text");

                    b.Property<bool>("Foil")
                        .HasColumnType("boolean");

                    b.Property<string>("ImageUri")
                        .HasColumnType("text");

                    b.Property<bool>("NonFoil")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("PriceEur")
                        .HasColumnType("numeric");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Set")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SetName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("Printings");
                });

            modelBuilder.Entity("MulliganDeck.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CardKeyword", b =>
                {
                    b.HasOne("MulliganDeck.Domain.Card", null)
                        .WithMany()
                        .HasForeignKey("CardsOracleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MulliganDeck.Domain.Keyword", null)
                        .WithMany()
                        .HasForeignKey("KeywordsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MulliganDeck.Domain.Card", b =>
                {
                    b.HasOne("MulliganDeck.Domain.Printing", "DefaultPrinting")
                        .WithMany()
                        .HasForeignKey("DefaultPrintingId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("DefaultPrinting");
                });

            modelBuilder.Entity("MulliganDeck.Domain.CollectionItem", b =>
                {
                    b.HasOne("MulliganDeck.Domain.Printing", "Printing")
                        .WithMany()
                        .HasForeignKey("PrintingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Printing");
                });

            modelBuilder.Entity("MulliganDeck.Domain.Deck", b =>
                {
                    b.HasOne("MulliganDeck.Domain.Card", "Commander")
                        .WithMany()
                        .HasForeignKey("CommanderId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Commander");
                });

            modelBuilder.Entity("MulliganDeck.Domain.DeckCard", b =>
                {
                    b.HasOne("MulliganDeck.Domain.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MulliganDeck.Domain.Deck", "Deck")
                        .WithMany("Cards")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MulliganDeck.Domain.Printing", "Printing")
                        .WithMany()
                        .HasForeignKey("PrintingId");

                    b.Navigation("Card");

                    b.Navigation("Deck");

                    b.Navigation("Printing");
                });

            modelBuilder.Entity("MulliganDeck.Domain.Legality", b =>
                {
                    b.HasOne("MulliganDeck.Domain.Card", "Card")
                        .WithMany("Legalities")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("MulliganDeck.Domain.Printing", b =>
                {
                    b.HasOne("MulliganDeck.Domain.Card", "Card")
                        .WithMany("Printings")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("MulliganDeck.Domain.Card", b =>
                {
                    b.Navigation("Legalities");

                    b.Navigation("Printings");
                });

            modelBuilder.Entity("MulliganDeck.Domain.Deck", b =>
                {
                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
